version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    volumes:
      - ./:/app
  postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: retail-crm-test
      PGDATA: /var/lib/postgresql/data/pgdata

